name: Contextos
run-name: Â¡Estoy aprendiendo a usar Contextos!
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
      age:
        description: 'Age of the user'
        default: 'World'
        required: true
        type: choice
        options:
        - Python
        - JavaScript
        - Go
env:
  #env_var: ${{ vars.ENV_CONTEXT_VAR }}
  var1: Aprendiendo
  var2: Github-Actions
  var3: Contextos
  
jobs:
  display-variables:
    #name: ${{ vars.JOB_NAME }}
    name: job_contextos
    # You can use configuration variables with the `vars` context for dynamic jobs
    if: ${{ vars.USE_VARIABLES == 'true' }}
    #runs-on: ${{ vars.RUNNER }}
    runs-on: ubuntu-latest
    #environment: ${{ vars.ENVIRONMENT_STAGE }}
    environment: staging
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "organization variable : $ORGANIZATION_VAR"
        echo "overridden variable : $OVERRIDE_VAR"
        echo "variable from shell environment : $env_var"
      env:
        REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
        OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}
        
    - name: ${{ vars.HELLO_WORLD_STEP }}
      if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ vars.GREET_NAME }}
