name: Expressions
run-name: ${{ github.actor }} is learning Expressions

on:
  workflow_dispatch:
    inputs:
      favorite_food:
        description: "Favorite food"
        default: Pizza
        required: true
        type: choice
        options:
          - Pizza
          - Tacos
      sauce:
        description: "Sauce"
        required: true
        default: Hot
        type: choice
        options:
          - Hot
          - Mild

jobs:
  pizza-job:
    if: ${{ github.event.inputs.favorite_food == 'Pizza' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pizza with ${{ github.event.inputs.sauce }} sauce"

  tacos-job:
    if: ${{ github.event.inputs.favorite_food == 'Tacos' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tacos with ${{ github.event.inputs.sauce }} sauce"
